- name: Add sensu repository
  yum_repository:
    name: sensu
    description: EPEL YUM repo
    baseurl: "{{ sensu_download_url }}"
    gpgcheck: no
    enabled: true
- name: Yum update and install sensu
  yum:
    name: sensu
    state: latest
    update_cache: true
- name: Configure /etc/sensu/conf.d/redis.json
  template:
    src: redis_json.j2
    dest: /etc/sensu/conf.d/redis.json
    owner: sensu
    group: sensu
    mode: 0644
- name: Configure /etc/sensu/conf.d/rabbitmq.json
  template:
    src: rabbitmq_json.j2
    dest: /etc/sensu/conf.d/rabbitmq.json
    owner: sensu
    group: sensu
    mode: 0644
- name: Configure /etc/sensu/conf.d/api.json
  template:
    src: api_json.j2
    dest: /etc/sensu/conf.d/api.json
    owner: sensu
    group: sensu
    mode: 0644
- name: Configure /etc/sensu/conf.d/client.json
  template:
    src: client_json.j2
    dest: /etc/sensu/conf.d/client.json
    owner: sensu
    group: sensu
    mode: 0644
- name: Configure /etc/sensu/conf.d/transport.json
  template:
    src: transport_json.j2
    dest: /etc/sensu/conf.d/transport.json
    owner: sensu
    group: sensu
    mode: 0644
- name: Enable and start sensu api and sensu client
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - sensu-api
    - sensu-client
- name: Check if firewalld is installed
  yum:
    list: firewalld
  register: firewalld_op
- name: Open tcp port {{ sensu-api-port }}for dashboard access
  firewalld:
    port: "{{ sensu_api_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: firewalld_op.results|selectattr("yumstate", "match", "installed")|list|length != 0
- name: Verify if sensu API is listening on TCP port {{ sensu_api_port }}
  get_url:
    url: "http://{{ ansible_default_ipv4.address }}:{{ sensu_api_port }}/info"
    dest: /tmp
  register: sensu_api_access
- fail:
    msg: "Sensu API is not listening on port {{ sensu_api_port }} on server {{ ansible_default_ipv4.address }}"
  when: sensu_api_access.status_code != 200
   
