- name: Copy sensu sudoers file in to /etc/sudoers.d
  copy:
    src: files/sensu
    dest: /etc/sudoers.d/
- name: Add sensu repository
  yum_repository:
    name: sensu
    description:  Sensu YUM repo
    baseurl: "{{ sensu_download_url }}"
    gpgcheck: no
    enabled: true
- name: Install sensu
  yum:
    name: sensu
    state: latest
- name: Configure sensu client for rabbitmq
  template:
    src: rabbitmq_json.j2
    dest: /etc/sensu/conf.d/rabbitmq.json
- name: Configure sensu client for checks
  template:
    src: client_json.j2
    dest: /etc/sensu/conf.d/client.json
- name: Start sensu client
  service:
    name: sensu-client
    state: restarted
