- name: Disable sensu repository
  yum_repository:
    name: sensu
    description: EPEL YUM repo
    baseurl: https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
    gpgcheck: no
    state: absent
- name: Remove sensu and uchiwa
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - sensu
    - uchiwa
- name: Remove sensu directory /etc/sensu
  file:
    path: /etc/sensu
    state: absent

    

